### PR TITLE
Automatic Reviews with LSTM

### PR DESCRIPTION
**Pull request by KvEijden**
The LSTM IMDB example adjusted for our data (articles selected by Rense)

### CODE REVIEW

**Comment by J535D165** [comment]
Split the R script? 

- One script with a function that reads the full dataset and adds the outcome variable. (dir R/utils)
- One script with the model part. (dir R/models)

@doab What are your thoughts?

**Comment by KvEijden** [comment]
The type of the model dictates in some way how the data must be encoded. The first script will then contain  several functions.  That shouldn't be a problem.

**Comment by daob** [comment]
@J535D165 @KvEijden:

Yes, the whole first pasrt of the script is merging the two and assigning labels based on the merge. That should be done in a separate file. I would also feel better if we used some more robust tools like dplyr::left_join instead of the part where it says %in%, and had a few test cases to double-check that everything went OK. 

Perhaps this script would write a csv file (title, abstract, included) that can be read in as the first step of subsequent analysis. 

And I am not sure why we are using json here. Is there some advantage to this over csv? If not I would prefer the csv's (actually didn't even commit the json output from the Makefile!).

**Comment by KvEijden** [comment]
Could we discuss the pro and cons of json versus csv in our meeting coming Thursday?
Then I will split the scripts.

**Comment by J535D165** [comment]
JSON(lines) fits the data better imo because it is a semi-structured dataset. `authors`, `keywords` and `notes` may contain multiple values. Especially `keywords` can be interesting for further analysis (A focussed LSTM?)

```
> glimpse(schoot_lgmm_ptsd_included_2)
Observations: 38
Variables: 31
$ X1                <int> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,...
$ abstract          <chr> "BACKGROUND: Traumatic injuries affect millions of patien...
$ access_date       <chr> NA, NA, "/", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
$ accession_number  <int> 25657356, NA, NA, NA, NA, NA, 25419860, 26401968, 2518889...
$ alternate_title1  <chr> "The British journal of psychiatry : the journal of menta...
$ author_address    <chr> "Richard A. Bryant, PhD, School of Psychology, University...
$ authors           <chr> "['Bryant, R. A.', 'Nickerson, A.', 'Creamer, M.', \"O'Do...
$ custom2           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Pmc46814...
$ custom6           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "Nihms742...
$ custom7           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...
$ database_provider <chr> "NLM", NA, NA, NA, NA, NA, "NLM", "NLM", "NLM", "NLM", "N...
$ date              <chr> "May", NA, NA, NA, NA, NA, "Nov 24", "Dec", "Sep", "Jan",...
$ doi               <chr> "10.1192/bjp.bp.114.145516", NA, NA, NA, "10.1037/a002080...
$ edition           <date> 2015-02-07, NA, NA, NA, NA, NA, 2014-11-25, 2015-09-25, ...
$ file_attachments1 <chr> "internal-pdf://1669821051/Bryant-2015-Trajectory of post...
$ id                <int> 41, 36, 3, 10, 53, 35, 39, 44, 24, 42, 40, 45, 47, 48, 34...
$ issn              <chr> "0007-1250", NA, NA, NA, NA, NA, "0021-843x", "0887-6185"...
$ keywords          <chr> "['Adolescent', 'Adult', 'Aged', 'Australia', 'Brain Inju...
$ language          <chr> "eng", NA, NA, NA, NA, NA, "Eng", "eng", "eng", "eng", "e...
$ name_of_database  <chr> NA, "Scopus", NA, NA, "Scopus", "Scopus", NA, NA, NA, NA,...
$ notes             <chr> "['1472-1465', 'Bryant, Richard A', 'Nickerson, Angela', ...
$ number            <chr> "5", "12", "4", NA, "5", NA, NA, NA, "9", "1", "1", "3", ...
$ secondary_title   <chr> "Br J Psychiatry", "Brain Injury", "British Journal of Ps...
$ short_title       <chr> "Trajectory of post-traumatic stress following traumatic ...
$ start_page        <chr> "417-23", "1542-1550", "317-323", "1-19", "484-495", NA, ...
$ title             <chr> "Trajectory of post-traumatic stress following traumatic ...
$ type_of_reference <chr> "JOUR", "JOUR", "JOUR", "JOUR", "JOUR", "JOUR", "JOUR", "...
$ type_of_work      <chr> NA, NA, NA, NA, "Article", NA, NA, NA, NA, NA, NA, NA, NA...
$ url               <chr> "http://bjp.rcpsych.org/content/bjprcpsych/206/5/417.full...
$ volume            <int> 206, 28, 200, NA, 29, NA, NA, 36, 75, 41, 28, 28, 28, NA,...
$ year              <int> 2015, 2014, 2012, 2013, 2010, 2014, 2014, 2015, 2014, 201...
```

**Comment by daob** [comment]
@J535D165 good point, I'm convinced.

This means we need to commit the json as well then :)

**Pull request closed without merging**
